package voting;

import java.io.FileNotFoundException;

public class Main {
    public static void main(String[] args){
        Rankings ranking;
        try {
            ranking = new Rankings(
                    "src/voting/categories.txt",
                    "src/voting/male.txt",
                    "src/voting/female.txt"
            );

            for (int i = 0; i < ranking.categories.length; i++) {
                System.out.println(STR."CATEGORY: \{ranking.categories[i]}" );
                System.out.println(STR."MALE WINNERS: \{ranking.getMaleTop3(i)}");
                System.out.println(STR."FEMALE WINNERS: \{ranking.getFemaleTop3(0)}");
                System.out.println();
            }
        } catch (FileNotFoundException e) {
            System.out.println(e);
        }
    }
}

/* OUTPUT
CATEGORY: Best Body
MALE WINNERS: [VITO MARSICO, CHRISTOPHER COX, BRANDON HANNAN]
FEMALE WINNERS: [CHRISTINA GUILHERME, ROSEMARI PAGANO, CHRISTINA CAPUTO]

CATEGORY: Talks the Most Says the Least
MALE WINNERS: [LEE GOCHMAN, RYAN FITZPATRICK, ANTHONY ROLLINO]
FEMALE WINNERS: [CHRISTINA GUILHERME, ROSEMARI PAGANO, CHRISTINA CAPUTO]

CATEGORY: Most likely to Succeed
MALE WINNERS: [RYAN LISANN, QUAN ZHOU, VICTOR LIAO]
FEMALE WINNERS: [CHRISTINA GUILHERME, ROSEMARI PAGANO, CHRISTINA CAPUTO]

CATEGORY: Class Clown
MALE WINNERS: [WILLIAM HABER, MYLES MCGEE, RICHARD MORRISON]
FEMALE WINNERS: [CHRISTINA GUILHERME, ROSEMARI PAGANO, CHRISTINA CAPUTO]

CATEGORY: Most Artistic
MALE WINNERS: [JOSEPH LOMONACO, AARON WITZER, ROBERT MOREL]
FEMALE WINNERS: [CHRISTINA GUILHERME, ROSEMARI PAGANO, CHRISTINA CAPUTO]

CATEGORY: Mr. & Ms. HS Name
MALE WINNERS: [KYLE SAMMIS, MICHAEL QUINN, NATHANIEL KRISTALL]
FEMALE WINNERS: [CHRISTINA GUILHERME, ROSEMARI PAGANO, CHRISTINA CAPUTO]

CATEGORY: Most Musical
MALE WINNERS: [VICTOR LIAO, NATHANIEL KRISTALL, KHALIL COOPER]
FEMALE WINNERS: [CHRISTINA GUILHERME, ROSEMARI PAGANO, CHRISTINA CAPUTO]

CATEGORY: Most Likely to Set the Next Big Fashion Trend
MALE WINNERS: [ROBERT MOREL, ABRAHAM ADAM, CHRISTOPHER COX]
FEMALE WINNERS: [CHRISTINA GUILHERME, ROSEMARI PAGANO, CHRISTINA CAPUTO]

CATEGORY: Worst Senioritis
MALE WINNERS: [MICHAEL MARINO, RICHARD MORRISON, SCOTT BALLEN]
FEMALE WINNERS: [CHRISTINA GUILHERME, ROSEMARI PAGANO, CHRISTINA CAPUTO]

CATEGORY: Cutest Couple
MALE WINNERS: [JAMES BARONE, JOSEPH RISCICA, TAYLOR BRUGNA]
FEMALE WINNERS: [CHRISTINA GUILHERME, ROSEMARI PAGANO, CHRISTINA CAPUTO]

CATEGORY: Most Likely to Brighten Up Your Day
MALE WINNERS: [KYLE FITZGERALD, GIANNI CURTO, RICHARD MORRISON]
FEMALE WINNERS: [CHRISTINA GUILHERME, ROSEMARI PAGANO, CHRISTINA CAPUTO]

CATEGORY: Most Desirable to Take Home to Your Parents
MALE WINNERS: [BENJAMIN BIEDERMAN, PERRY KOENIG, GIANNI CURTO]
FEMALE WINNERS: [CHRISTINA GUILHERME, ROSEMARI PAGANO, CHRISTINA CAPUTO]

CATEGORY: Most Likely to be Seen Fist Pumping on the Jersey Shore.
MALE WINNERS: [GIANNI CURTO, GINO MACCHIO, RICHARD MORRISON]
FEMALE WINNERS: [CHRISTINA GUILHERME, ROSEMARI PAGANO, CHRISTINA CAPUTO]

CATEGORY: Beauty/Brawn/Brains
MALE WINNERS: [KYLE SAMMIS, CHRISTOPHER BUSUTTIL, BENJAMIN BIEDERMAN]
FEMALE WINNERS: [CHRISTINA GUILHERME, ROSEMARI PAGANO, CHRISTINA CAPUTO]

CATEGORY: Most Athletic
MALE WINNERS: [TAVON SLEDGE, MICHAEL CRISPI, JUSTIN CONNOR]
FEMALE WINNERS: [CHRISTINA GUILHERME, ROSEMARI PAGANO, CHRISTINA CAPUTO]

CATEGORY: Billion $ Smile
MALE WINNERS: [CHRISTOPHER COX, LUKE KOHAN, ABDIAS MYRTIL]
FEMALE WINNERS: [CHRISTINA GUILHERME, ROSEMARI PAGANO, CHRISTINA CAPUTO]
 */
